# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'kimt'
    sourceRepo: 'eytanr-npm'

- task: JFrogNpm@1
  inputs:
    command: 'pack and publish'
    artifactoryConnection: 'kimt'
    targetRepo: 'eytanr-npm'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'kimt cli'
    command: |
      jf npmc --server-id-resolve='' --server-id-deploy='' --repo-resolve='eytanr-npm' --repo-deploy='eytanr-npm'
      jf npm install --build-name=etnbuild --build-number=1.0.0
      jf publish --build-name=etnbuild --build-number=1.0.0
      jf bs etnbuild 1.0.0
  
- task: JFrogAudit@1
  inputs:
    xrayConnection: 'kimt2'
    watchesSource: 'none'
    licenses: false