# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

steps:
- script: |
    echo "Fetching the latest JFrog CLI version..."
    latestVersion=$(curl -s https://api.github.com/repos/jfrog/jfrog-cli/releases/latest | jq -r '.tag_name' | sed 's/^v//')
    echo "##vso[task.setvariable variable=jfrogCliVersion]$latestVersion"
  displayName: 'Set jfrogCliVersion to the latest version'


- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'idani25plat'
    useCustomVersion: true
    cliVersion: '$(jfrogCliVersion)'
    command: |
      jf rt ping

- task: JFrogAudit@1
  inputs:
    xrayConnection: 'kimt2'
    watchesSource: 'none'
    licenses: false
    args: '--format=json'


- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'idani'
    sourceRepo: 'etnpm-npm'

- task: JFrogNpm@1
  inputs:
    command: 'pack and publish'
    artifactoryConnection: 'idani'
    targetRepo: 'etnpm-npm'

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'idanix'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false
    vuln: false

  
