name: "Setup JFrog CLI OIDC Example"
on: push

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      # Define your image name here for consistency
      IMAGE_NAME: ${{ vars.JF_URL }}/docker-local/juice-shop:${{ github.sha }}
      JF_URL: ${{ vars.JF_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: BiggieFudge/juice-shop@github

      - name: Ping JFrog (Optional)
        run: jf rt ping
        
      - name: Build Docker Image
        run: |
          # Build the image locally
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: JFrog Docker Scan
        run: |
          # Scan the image using JFrog Xray
          jf docker scan ${{ env.IMAGE_NAME }}

